[package]
name = "mallet"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.3"
color-eyre = "0.6.3"
serde = { version = "1.0.219", features = ["derive"] }
ulid = { version = "1.2.1", features = ["serde"] }
